# Generated by Django 4.1.6 on 2023-02-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regiastration_date',
            new_name='registration_date',
        ),
    ]
